version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Backend:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      
  celery_worker:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./Backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
